export const CREATE_LIST = "CREATE_LIST";
export const GET_LIST = "GET_LIST";
export const DELETE_LIST = "DELETE_LIST";
export const UPDATE_LIST = "UPDATE_LIST";
export const BREADCRUMB_PATH_CHANGED = "BREADCRUMB_PATH_CHANGED";
